version: '3.8'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Europe/Helsinki
      PGTZ: Europe/Helsinki
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
      - "5432:5432"
    command: 
      - "postgres"
      - "-c"
      - "timezone=Europe/Helsinki"
      - "-c"
      - "datestyle=ISO, DMY"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/myapp
      TZ: Europe/Helsinki
      PORT: ${BACKEND_PORT:-3000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-3000}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data: